# Generated by Django 4.2.3 on 2023-08-11 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamediscount',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamediscount',
            name='gameFinalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamediscount',
            name='gameId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamediscount',
            name='gameInitialPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='gameId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamediscount',
            name='currency',
            field=models.CharField(default='ca', max_length=4),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='gameImages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, null=True), null=True, size=None),
        ),
    ]
