# Generated by Django 4.2.3 on 2023-08-11 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_gameid_gamediscount_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='gameImages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='headImageURL',
            field=models.CharField(max_length=256),
        ),
    ]
